<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Grade Report - {{ $semester->name }}</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            color: #333;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }
        .header h1 {
            font-size: 18px;
            margin: 0 0 5px 0;
        }
        .header h2 {
            font-size: 14px;
            font-weight: normal;
            margin: 0 0 5px 0;
            color: #555;
        }
        .header p {
            font-size: 10px;
            color: #777;
            margin: 3px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th {
            background-color: #f3f4f6;
            border: 1px solid #d1d5db;
            padding: 8px 6px;
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
            color: #374151;
        }
        td {
            border: 1px solid #d1d5db;
            padding: 6px;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background-color: #f9fafb;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
        .font-bold {
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            border-top: 1px solid #d1d5db;
            padding-top: 10px;
            font-size: 9px;
            color: #6b7280;
        }
        .grade-badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            background-color: #dbeafe;
            color: #1e40af;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Assessment Management System</h1>
        <h2>Consolidated Grade Report</h2>
        <p>Semester: {{ $semester->name }} ({{ $semester->academic_year }})</p>
        <p>Generated: {{ $generatedAt->format('d M Y, H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>University ID</th>
                <th>Student Name</th>
                <th>Project Title</th>
                <th class="text-right">Calculated</th>
                <th class="text-right">Final Score</th>
                <th class="text-center">Grade</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($rows as $row)
                <tr>
                    <td class="font-bold">{{ $row['university_id'] }}</td>
                    <td>{{ $row['student_name'] }}</td>
                    <td>{{ Str::limit($row['project_title'], 45) }}</td>
                    <td class="text-right">{{ $row['calculated_score'] }}</td>
                    <td class="text-right font-bold">{{ $row['final_score'] }}</td>
                    <td class="text-center">
                        <span class="grade-badge">{{ $row['letter_grade'] }}</span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Students: {{ count($rows) }}</p>
        <p>Generated by: {{ $generatedBy }}</p>
        <p>This is a system-generated document from the Assessment Management System.</p>
    </div>
</body>
</html>
